CREATE DATABASE IF NOT EXISTS `dashboard` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `dashboard`;

DROP TABLE IF EXISTS `User`;

CREATE TABLE IF NOT EXISTS `User`
(
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `horloge` VARCHAR(100) DEFAULT NULL,
  `facebook` VARCHAR(100) DEFAULT NULL,
  `twitter` VARCHAR(100) DEFAULT NULL,
  `youtube` VARCHAR(100) DEFAULT NULL,
  `gplus` VARCHAR(100) DEFAULT NULL,
  `github` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE (`Name`)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;
