CREATE DATABASE IF NOT EXISTS `dashboard` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `dashboard`;

DROP TABLE IF EXISTS `User`;

CREATE TABLE IF NOT EXISTS `User`
(
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `TokenHorloge` VARCHAR(100) DEFAULT NULL,
  `TokenFacebook` VARCHAR(100) DEFAULT NULL,
  `TokenTwitter` VARCHAR(100) DEFAULT NULL,
  `TokenYoutube` VARCHAR(100) DEFAULT NULL,
  `TokenGooglePlus` VARCHAR(100) DEFAULT NULL,
  `TokenGithub` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE (`Name`)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;
